-- Admin data dashboard: allowlist, shared draft, publish history.
-- Run once in the Supabase SQL Editor AFTER add_tract_geoid_column.sql.
-- Idempotent: safe to re-run (it never overwrites an existing draft or history).
--
-- The live table `projects_merged_conf1` and its columns are left exactly as
-- they are (they are cited in published work); this script only adds tables
-- and functions alongside it.
--
--   admin_users        emails allowed to use /admin
--   projects_draft     the shared working copy edited in /admin (same columns
--                      as projects_merged_conf1)
--   projects_versions  a full snapshot of every publish (restore source)
--
--   save_draft_changes(...)      apply one "Save draft" (updates, inserts, deletes) atomically
--   publish_draft(note)          snapshot draft -> new version, replace projects_merged_conf1 rows
--   restore_version(version_id)  copy a version's snapshot back into the draft (does not publish)
--   reset_draft_from_published() discard all unpublished draft changes
--
--   filters_draft / filters_versions and their functions: the map filter
--   settings edited on /admin/live-tool (see the section near the end).
--
-- Row ids come from one shared sequence, so a project keeps the same id in the
-- draft, in projects_merged_conf1 and in every snapshot. The /admin diffs rely on it.

-- ── Allowlist ───────────────────────────────────────────────────────────────

create table if not exists public.admin_users (
  email text primary key check (email = lower(email)),
  added_at timestamptz not null default now()
);

-- Edit these before running. Each email also needs a Supabase Auth user
-- (Authentication → Users → Add user).
insert into public.admin_users (email) values
  ('axm8832@miami.edu'),
  ('spraharaj@miami.edu')
on conflict (email) do nothing;

alter table public.admin_users enable row level security;
-- No policies: the table is only read through is_admin().

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users
    where email = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

-- ── Shared row id sequence ──────────────────────────────────────────────────

create sequence if not exists public.projects_row_id_seq;

select setval(
  'public.projects_row_id_seq',
  greatest(
    (select last_value from public.projects_row_id_seq),
    coalesce((select max(id) from public.projects_merged_conf1), 0),
    1
  )
);

-- ── Draft ───────────────────────────────────────────────────────────────────

create table if not exists public.projects_draft (
  id bigint primary key default nextval('public.projects_row_id_seq'),
  project_na text,
  name text,
  city text,
  latitude double precision,
  longitude double precision,
  infrastruc text,
  categories text,
  disaster_f text,
  new_15_25_ text,
  project_st text,
  project_en text,
  project_status text,
  status_category text,
  estimated_cost double precision,
  implementa text,
  link_to_da text,
  additional text,
  tract_geoid text,
  updated_at timestamptz not null default now(),
  updated_by text
);

-- `name` duplicates `city` and `categories` duplicates `additional` in the
-- seeded data. /admin only edits `city` and `additional`, so keep the
-- duplicates in step unless they had already diverged.
create or replace function public.projects_draft_touch()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' then
    new.name := coalesce(new.name, new.city);
    new.categories := coalesce(new.categories, new.additional);
  else
    if new.city is distinct from old.city and old.name is not distinct from old.city then
      new.name := new.city;
    end if;
    if new.additional is distinct from old.additional and old.categories is not distinct from old.additional then
      new.categories := new.additional;
    end if;
  end if;
  new.updated_at := now();
  new.updated_by := coalesce(auth.jwt() ->> 'email', new.updated_by);
  return new;
end;
$$;

drop trigger if exists projects_draft_touch on public.projects_draft;
create trigger projects_draft_touch
  before insert or update on public.projects_draft
  for each row execute function public.projects_draft_touch();

alter table public.projects_draft enable row level security;

drop policy if exists "projects_draft admin all" on public.projects_draft;
create policy "projects_draft admin all"
  on public.projects_draft for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- ── Versions ────────────────────────────────────────────────────────────────

create table if not exists public.projects_versions (
  id bigint generated by default as identity primary key,
  version_no integer not null unique,
  created_at timestamptz not null default now(),
  created_by text,
  note text not null,
  row_count integer not null,
  snapshot jsonb not null,
  is_current boolean not null default false
);

create unique index if not exists projects_versions_one_current
  on public.projects_versions (is_current) where is_current;

alter table public.projects_versions enable row level security;

drop policy if exists "projects_versions admin read" on public.projects_versions;
create policy "projects_versions admin read"
  on public.projects_versions for select
  to authenticated
  using (public.is_admin());
-- No write policies: versions are only changed through the functions below
-- (publish_draft, make_version_live, rename_version, delete_version).

-- Optional display name; the publish note stays as the record of the change.
alter table public.projects_versions add column if not exists name text;

create or replace function public.rename_version(p_version_id bigint, p_name text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_name text := nullif(btrim(coalesce(p_name, '')), '');
begin
  if not public.is_admin() then
    raise exception 'Only admins can rename versions' using errcode = '42501';
  end if;
  if length(v_name) > 120 then
    raise exception 'Version names can be at most 120 characters' using errcode = '22023';
  end if;

  update public.projects_versions set name = v_name where id = p_version_id;
  if not found then
    raise exception 'Version % not found', p_version_id using errcode = 'P0002';
  end if;

  return jsonb_build_object('id', p_version_id, 'name', v_name);
end;
$$;

revoke all on function public.rename_version(bigint, text) from public, anon;
grant execute on function public.rename_version(bigint, text) to authenticated;

-- Permanently removes a past version. The live version cannot be deleted.
-- Numbers come from projects_version_no_seq, so they are never reused.
create or replace function public.delete_version(p_version_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_version_no integer;
  v_is_current boolean;
begin
  if not public.is_admin() then
    raise exception 'Only admins can delete versions' using errcode = '42501';
  end if;

  select version_no, is_current into v_version_no, v_is_current
  from public.projects_versions where id = p_version_id
  for update;
  if v_version_no is null then
    raise exception 'Version % not found', p_version_id using errcode = 'P0002';
  end if;
  if v_is_current then
    raise exception 'Version % is live on the map and cannot be deleted', v_version_no using errcode = '22023';
  end if;

  delete from public.projects_versions where id = p_version_id;

  return jsonb_build_object('id', p_version_id, 'version_no', v_version_no);
end;
$$;

revoke all on function public.delete_version(bigint) from public, anon;
grant execute on function public.delete_version(bigint) to authenticated;

-- ── Initial state: version 1 = today's live data; draft = copy of live ──────

do $$
begin
  if not exists (select 1 from public.projects_versions) then
    insert into public.projects_versions (version_no, created_by, note, row_count, snapshot, is_current)
    select
      1,
      'system',
      'Initial snapshot of projects_merged_conf1 when the admin dashboard was set up',
      count(*),
      coalesce(jsonb_agg(to_jsonb(p) order by p.id), '[]'::jsonb),
      true
    from public.projects_merged_conf1 p;
  end if;
end $$;

-- Version numbers come from a counter rather than max()+1: any version can be
-- made live and any other deleted, so the highest number may be deleted.
create sequence if not exists public.projects_version_no_seq;

do $$
begin
  perform setval(
    'public.projects_version_no_seq',
    greatest(
      (select last_value from public.projects_version_no_seq),
      coalesce((select max(version_no) from public.projects_versions), 0),
      1
    )
  );
end $$;

insert into public.projects_draft (
  id, project_na, name, city, latitude, longitude, infrastruc, categories,
  disaster_f, new_15_25_, project_st, project_en, project_status, status_category,
  estimated_cost, implementa, link_to_da, additional, tract_geoid, updated_by
)
select
  id, project_na, name, city, latitude, longitude, infrastruc, categories,
  disaster_f, new_15_25_, project_st, project_en, project_status, status_category,
  estimated_cost, implementa, link_to_da, additional, tract_geoid, 'system'
from public.projects_merged_conf1
where not exists (select 1 from public.projects_draft);

-- ── admin_published_rows ────────────────────────────────────────────────────
-- Lets /admin read the live rows (to show unpublished changes) without adding
-- policies to projects_merged_conf1.

create or replace function public.admin_published_rows()
returns setof public.projects_merged_conf1
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Only admins can read the live rows here' using errcode = '42501';
  end if;
  return query select * from public.projects_merged_conf1;
end;
$$;

revoke all on function public.admin_published_rows() from public, anon;
grant execute on function public.admin_published_rows() to authenticated;

-- ── save_draft_changes ──────────────────────────────────────────────────────
-- Applies one "Save draft" from /admin atomically. Runs as the caller, so the
-- projects_draft RLS policy (admins only) still applies.
--   p_updates  jsonb array of full rows with existing ids
--   p_inserts  jsonb array of new rows (ids assigned here)
--   p_deletes  ids to remove

create or replace function public.save_draft_changes(
  p_updates jsonb default '[]'::jsonb,
  p_inserts jsonb default '[]'::jsonb,
  p_deletes bigint[] default '{}'
)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_deleted integer;
  v_updated integer;
  v_inserted integer;
begin
  if not public.is_admin() then
    raise exception 'Only admins can edit the draft' using errcode = '42501';
  end if;

  delete from public.projects_draft where id = any(coalesce(p_deletes, '{}'));
  get diagnostics v_deleted = row_count;

  update public.projects_draft d set
    implementa = r.implementa,
    project_na = r.project_na,
    city = r.city,
    latitude = r.latitude,
    longitude = r.longitude,
    link_to_da = r.link_to_da,
    infrastruc = r.infrastruc,
    disaster_f = r.disaster_f,
    new_15_25_ = r.new_15_25_,
    project_status = r.project_status,
    status_category = r.status_category,
    estimated_cost = r.estimated_cost,
    project_st = r.project_st,
    additional = r.additional,
    tract_geoid = r.tract_geoid
  from jsonb_populate_recordset(null::public.projects_draft, coalesce(p_updates, '[]'::jsonb)) r
  where d.id = r.id;
  get diagnostics v_updated = row_count;

  insert into public.projects_draft (
    implementa, project_na, city, latitude, longitude, link_to_da, infrastruc,
    disaster_f, new_15_25_, project_status, status_category, estimated_cost,
    project_st, additional, tract_geoid
  )
  select
    r.implementa, r.project_na, r.city, r.latitude, r.longitude, r.link_to_da, r.infrastruc,
    r.disaster_f, r.new_15_25_, r.project_status, r.status_category, r.estimated_cost,
    r.project_st, r.additional, r.tract_geoid
  from jsonb_populate_recordset(null::public.projects_draft, coalesce(p_inserts, '[]'::jsonb)) r;
  get diagnostics v_inserted = row_count;

  return jsonb_build_object('deleted', v_deleted, 'updated', v_updated, 'inserted', v_inserted);
end;
$$;

revoke all on function public.save_draft_changes(jsonb, jsonb, bigint[]) from public, anon;
grant execute on function public.save_draft_changes(jsonb, jsonb, bigint[]) to authenticated;

-- ── publish_draft ───────────────────────────────────────────────────────────

create or replace function public.publish_draft(p_note text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_email text := lower(coalesce(auth.jwt() ->> 'email', ''));
  v_version_no integer;
  v_version_id bigint;
  v_row_count integer;
begin
  if not public.is_admin() then
    raise exception 'Only admins can publish' using errcode = '42501';
  end if;
  if p_note is null or btrim(p_note) = '' then
    raise exception 'A publish note is required' using errcode = '22023';
  end if;

  -- Serialize concurrent publishes.
  perform pg_advisory_xact_lock(hashtext('publish_draft'));

  v_version_no := nextval('public.projects_version_no_seq');

  update public.projects_versions set is_current = false where is_current;

  insert into public.projects_versions (version_no, created_by, note, row_count, snapshot, is_current)
  select
    v_version_no,
    v_email,
    btrim(p_note),
    count(*),
    coalesce(jsonb_agg(to_jsonb(d) - 'updated_at' - 'updated_by' order by d.id), '[]'::jsonb),
    true
  from public.projects_draft d
  returning id, row_count into v_version_id, v_row_count;

  -- Supabase's safeupdate extension rejects DELETE without a WHERE clause.
  delete from public.projects_merged_conf1 where true;

  insert into public.projects_merged_conf1 (
    id, project_na, name, city, latitude, longitude, infrastruc, categories,
    disaster_f, new_15_25_, project_st, project_en, project_status, status_category,
    estimated_cost, implementa, link_to_da, additional, tract_geoid
  )
  select
    id, project_na, name, city, latitude, longitude, infrastruc, categories,
    disaster_f, new_15_25_, project_st, project_en, project_status, status_category,
    estimated_cost, implementa, link_to_da, additional, tract_geoid
  from public.projects_draft;

  return jsonb_build_object(
    'version_id', v_version_id,
    'version_no', v_version_no,
    'row_count', v_row_count
  );
end;
$$;

revoke all on function public.publish_draft(text) from public, anon;
grant execute on function public.publish_draft(text) to authenticated;

-- ── make_version_live ───────────────────────────────────────────────────────
-- Puts a past version back on the map without creating a new version: replaces
-- projects_merged_conf1 and the draft with its snapshot and marks it current.
-- Called by the publish-projects edge function, which then rebuilds the GeoJSON.

create or replace function public.make_version_live(p_version_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_snapshot jsonb;
  v_version_no integer;
  v_row_count integer;
begin
  if not public.is_admin() then
    raise exception 'Only admins can change the live version' using errcode = '42501';
  end if;

  perform pg_advisory_xact_lock(hashtext('publish_draft'));

  select snapshot, version_no into v_snapshot, v_version_no
  from public.projects_versions where id = p_version_id
  for update;
  if v_snapshot is null then
    raise exception 'Version % not found', p_version_id using errcode = 'P0002';
  end if;

  update public.projects_versions set is_current = false where is_current and id <> p_version_id;
  update public.projects_versions set is_current = true where id = p_version_id;

  delete from public.projects_merged_conf1 where true;

  insert into public.projects_merged_conf1 (
    id, project_na, name, city, latitude, longitude, infrastruc, categories,
    disaster_f, new_15_25_, project_st, project_en, project_status, status_category,
    estimated_cost, implementa, link_to_da, additional, tract_geoid
  )
  select
    r.id, r.project_na, r.name, r.city, r.latitude, r.longitude, r.infrastruc, r.categories,
    r.disaster_f, r.new_15_25_, r.project_st, r.project_en, r.project_status, r.status_category,
    r.estimated_cost, r.implementa, r.link_to_da, r.additional, r.tract_geoid
  from jsonb_populate_recordset(null::public.projects_draft, v_snapshot) r;

  get diagnostics v_row_count = row_count;

  delete from public.projects_draft where true;

  insert into public.projects_draft (
    id, project_na, name, city, latitude, longitude, infrastruc, categories,
    disaster_f, new_15_25_, project_st, project_en, project_status, status_category,
    estimated_cost, implementa, link_to_da, additional, tract_geoid
  )
  select
    id, project_na, name, city, latitude, longitude, infrastruc, categories,
    disaster_f, new_15_25_, project_st, project_en, project_status, status_category,
    estimated_cost, implementa, link_to_da, additional, tract_geoid
  from public.projects_merged_conf1;

  perform setval(
    'public.projects_row_id_seq',
    greatest(
      (select last_value from public.projects_row_id_seq),
      coalesce((select max(id) from public.projects_merged_conf1), 0),
      1
    )
  );

  return jsonb_build_object(
    'version_id', p_version_id,
    'version_no', v_version_no,
    'row_count', v_row_count
  );
end;
$$;

revoke all on function public.make_version_live(bigint) from public, anon;
grant execute on function public.make_version_live(bigint) to authenticated;

-- ── restore_version ─────────────────────────────────────────────────────────

create or replace function public.restore_version(p_version_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_snapshot jsonb;
  v_version_no integer;
  v_row_count integer;
begin
  if not public.is_admin() then
    raise exception 'Only admins can restore versions' using errcode = '42501';
  end if;

  select snapshot, version_no into v_snapshot, v_version_no
  from public.projects_versions where id = p_version_id;
  if v_snapshot is null then
    raise exception 'Version % not found', p_version_id using errcode = 'P0002';
  end if;

  delete from public.projects_draft where true;

  insert into public.projects_draft (
    id, project_na, name, city, latitude, longitude, infrastruc, categories,
    disaster_f, new_15_25_, project_st, project_en, project_status, status_category,
    estimated_cost, implementa, link_to_da, additional, tract_geoid
  )
  select
    r.id, r.project_na, r.name, r.city, r.latitude, r.longitude, r.infrastruc, r.categories,
    r.disaster_f, r.new_15_25_, r.project_st, r.project_en, r.project_status, r.status_category,
    r.estimated_cost, r.implementa, r.link_to_da, r.additional, r.tract_geoid
  from jsonb_populate_recordset(null::public.projects_draft, v_snapshot) r;

  get diagnostics v_row_count = row_count;

  return jsonb_build_object('version_no', v_version_no, 'row_count', v_row_count);
end;
$$;

revoke all on function public.restore_version(bigint) from public, anon;
grant execute on function public.restore_version(bigint) to authenticated;

-- ── reset_draft_from_published ──────────────────────────────────────────────
-- Discards every unpublished draft change. Also run this after
-- `npm run seed-merged-conf1`, which reloads projects_merged_conf1 with new ids.

create or replace function public.reset_draft_from_published()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row_count integer;
begin
  -- auth.jwt() is null in the SQL Editor, so allow that path as well.
  if auth.jwt() is not null and not public.is_admin() then
    raise exception 'Only admins can reset the draft' using errcode = '42501';
  end if;

  delete from public.projects_draft where true;

  insert into public.projects_draft (
    id, project_na, name, city, latitude, longitude, infrastruc, categories,
    disaster_f, new_15_25_, project_st, project_en, project_status, status_category,
    estimated_cost, implementa, link_to_da, additional, tract_geoid
  )
  select
    id, project_na, name, city, latitude, longitude, infrastruc, categories,
    disaster_f, new_15_25_, project_st, project_en, project_status, status_category,
    estimated_cost, implementa, link_to_da, additional, tract_geoid
  from public.projects_merged_conf1;

  get diagnostics v_row_count = row_count;

  perform setval(
    'public.projects_row_id_seq',
    greatest(
      (select last_value from public.projects_row_id_seq),
      coalesce((select max(id) from public.projects_merged_conf1), 0),
      1
    )
  );

  return jsonb_build_object('row_count', v_row_count);
end;
$$;

revoke all on function public.reset_draft_from_published() from public, anon;
grant execute on function public.reset_draft_from_published() to authenticated;

-- ── Map filter settings (/admin/live-tool) ─────────────────────────────────
-- Which filters the public map shows and how their values are labelled,
-- colored and ordered. Published separately from the project data, to
-- project-data/filters_config.json, by the publish-projects edge function.
-- With no published filter version the map uses its built-in filters.
--
--   filters_draft     the single shared working copy (one row)
--   filters_versions  every published config (revert source)

create table if not exists public.filters_draft (
  id boolean primary key default true check (id),
  config jsonb not null,
  updated_at timestamptz not null default now(),
  updated_by text
);

alter table public.filters_draft enable row level security;

drop policy if exists "filters_draft admin read" on public.filters_draft;
create policy "filters_draft admin read"
  on public.filters_draft for select
  to authenticated
  using (public.is_admin());

create table if not exists public.filters_versions (
  id bigint generated by default as identity primary key,
  version_no integer not null unique,
  name text,
  note text not null,
  config jsonb not null,
  is_current boolean not null default false,
  created_at timestamptz not null default now(),
  created_by text
);

create unique index if not exists filters_versions_one_current
  on public.filters_versions (is_current) where is_current;

alter table public.filters_versions enable row level security;

drop policy if exists "filters_versions admin read" on public.filters_versions;
create policy "filters_versions admin read"
  on public.filters_versions for select
  to authenticated
  using (public.is_admin());

create sequence if not exists public.filters_version_no_seq;

do $$
begin
  perform setval(
    'public.filters_version_no_seq',
    greatest(
      (select last_value from public.filters_version_no_seq),
      coalesce((select max(version_no) from public.filters_versions), 0),
      1
    ),
    exists (select 1 from public.filters_versions)
  );
end $$;

create or replace function public.save_filters_draft(p_config jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_admin() then
    raise exception 'Only admins can edit the map filters' using errcode = '42501';
  end if;
  if p_config is null or jsonb_typeof(p_config -> 'filters') is distinct from 'array' then
    raise exception 'The filter settings must contain a filters list' using errcode = '22023';
  end if;

  insert into public.filters_draft (id, config, updated_at, updated_by)
  values (true, p_config, now(), lower(coalesce(auth.jwt() ->> 'email', '')))
  on conflict (id) do update
    set config = excluded.config, updated_at = excluded.updated_at, updated_by = excluded.updated_by;

  return jsonb_build_object('ok', true);
end;
$$;

revoke all on function public.save_filters_draft(jsonb) from public, anon;
grant execute on function public.save_filters_draft(jsonb) to authenticated;

-- Publishes the saved draft as a new filter version and makes it current.
create or replace function public.publish_filters(p_note text, p_name text default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_config jsonb;
  v_version_no integer;
  v_version_id bigint;
  v_name text := nullif(btrim(coalesce(p_name, '')), '');
begin
  if not public.is_admin() then
    raise exception 'Only admins can publish the map filters' using errcode = '42501';
  end if;
  if p_note is null or btrim(p_note) = '' then
    raise exception 'A publish note is required' using errcode = '22023';
  end if;
  if length(v_name) > 120 then
    raise exception 'Version names can be at most 120 characters' using errcode = '22023';
  end if;

  perform pg_advisory_xact_lock(hashtext('publish_filters'));

  select config into v_config from public.filters_draft where id;
  if v_config is null then
    raise exception 'Save the filter draft before publishing' using errcode = '22023';
  end if;

  v_version_no := nextval('public.filters_version_no_seq');
  update public.filters_versions set is_current = false where is_current;
  insert into public.filters_versions (version_no, name, note, config, is_current, created_by)
  values (v_version_no, v_name, btrim(p_note), v_config, true, lower(coalesce(auth.jwt() ->> 'email', '')))
  returning id into v_version_id;

  return jsonb_build_object('version_id', v_version_id, 'version_no', v_version_no, 'config', v_config);
end;
$$;

revoke all on function public.publish_filters(text, text) from public, anon;
grant execute on function public.publish_filters(text, text) to authenticated;

-- Puts a past filter version back on the map (no new version) and resets the
-- draft to it.
create or replace function public.make_filters_version_live(p_version_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_config jsonb;
  v_version_no integer;
begin
  if not public.is_admin() then
    raise exception 'Only admins can change the live map filters' using errcode = '42501';
  end if;

  perform pg_advisory_xact_lock(hashtext('publish_filters'));

  select config, version_no into v_config, v_version_no
  from public.filters_versions where id = p_version_id
  for update;
  if v_config is null then
    raise exception 'Filter version % not found', p_version_id using errcode = 'P0002';
  end if;

  update public.filters_versions set is_current = false where is_current and id <> p_version_id;
  update public.filters_versions set is_current = true where id = p_version_id;

  insert into public.filters_draft (id, config, updated_at, updated_by)
  values (true, v_config, now(), lower(coalesce(auth.jwt() ->> 'email', '')))
  on conflict (id) do update
    set config = excluded.config, updated_at = excluded.updated_at, updated_by = excluded.updated_by;

  return jsonb_build_object('version_id', p_version_id, 'version_no', v_version_no, 'config', v_config);
end;
$$;

revoke all on function public.make_filters_version_live(bigint) from public, anon;
grant execute on function public.make_filters_version_live(bigint) to authenticated;

-- Loads a filter version into the draft (does not publish).
create or replace function public.restore_filters_version(p_version_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_config jsonb;
  v_version_no integer;
begin
  if not public.is_admin() then
    raise exception 'Only admins can restore filter versions' using errcode = '42501';
  end if;

  select config, version_no into v_config, v_version_no
  from public.filters_versions where id = p_version_id;
  if v_config is null then
    raise exception 'Filter version % not found', p_version_id using errcode = 'P0002';
  end if;

  insert into public.filters_draft (id, config, updated_at, updated_by)
  values (true, v_config, now(), lower(coalesce(auth.jwt() ->> 'email', '')))
  on conflict (id) do update
    set config = excluded.config, updated_at = excluded.updated_at, updated_by = excluded.updated_by;

  return jsonb_build_object('version_no', v_version_no);
end;
$$;

revoke all on function public.restore_filters_version(bigint) from public, anon;
grant execute on function public.restore_filters_version(bigint) to authenticated;

create or replace function public.rename_filters_version(p_version_id bigint, p_name text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_name text := nullif(btrim(coalesce(p_name, '')), '');
begin
  if not public.is_admin() then
    raise exception 'Only admins can rename filter versions' using errcode = '42501';
  end if;
  if length(v_name) > 120 then
    raise exception 'Version names can be at most 120 characters' using errcode = '22023';
  end if;

  update public.filters_versions set name = v_name where id = p_version_id;
  if not found then
    raise exception 'Filter version % not found', p_version_id using errcode = 'P0002';
  end if;

  return jsonb_build_object('id', p_version_id, 'name', v_name);
end;
$$;

revoke all on function public.rename_filters_version(bigint, text) from public, anon;
grant execute on function public.rename_filters_version(bigint, text) to authenticated;

create or replace function public.delete_filters_version(p_version_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_version_no integer;
  v_is_current boolean;
begin
  if not public.is_admin() then
    raise exception 'Only admins can delete filter versions' using errcode = '42501';
  end if;

  select version_no, is_current into v_version_no, v_is_current
  from public.filters_versions where id = p_version_id
  for update;
  if v_version_no is null then
    raise exception 'Filter version % not found', p_version_id using errcode = 'P0002';
  end if;
  if v_is_current then
    raise exception 'Filter version % is live on the map and cannot be deleted', v_version_no using errcode = '22023';
  end if;

  delete from public.filters_versions where id = p_version_id;

  return jsonb_build_object('id', p_version_id, 'version_no', v_version_no);
end;
$$;

revoke all on function public.delete_filters_version(bigint) from public, anon;
grant execute on function public.delete_filters_version(bigint) to authenticated;

-- Discards the saved filter draft: back to the live version, or to the map's
-- built-in filters when nothing has been published yet (no draft row).
create or replace function public.reset_filters_draft()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_config jsonb;
begin
  if not public.is_admin() then
    raise exception 'Only admins can reset the filter draft' using errcode = '42501';
  end if;

  select config into v_config from public.filters_versions where is_current;
  if v_config is null then
    delete from public.filters_draft where id;
  else
    insert into public.filters_draft (id, config, updated_at, updated_by)
    values (true, v_config, now(), lower(coalesce(auth.jwt() ->> 'email', '')))
    on conflict (id) do update
      set config = excluded.config, updated_at = excluded.updated_at, updated_by = excluded.updated_by;
  end if;

  return jsonb_build_object('ok', true);
end;
$$;

revoke all on function public.reset_filters_draft() from public, anon;
grant execute on function public.reset_filters_draft() to authenticated;

-- Make the Supabase API pick up new columns and functions immediately.
notify pgrst, 'reload schema';

-- After `npm run seed-merged-conf1`, run in the SQL Editor:
--   select public.reset_draft_from_published();
